export type ProductGuideStep = {
  title: string;
  body: string;
  userFeeling: string;
  insights: string[];
  anchor: string;
  position: string;
  arrow: string;
  highlight: string;
};

const searchGuideStep: ProductGuideStep = {
  title: '상단 통합 검색',
  body: '검색창은 지금 보는 화면과 별개로 AXIS 전체 자료를 바로 여는 진입점입니다. 왼쪽 범위 선택으로 전체, 브리핑, Peer+, 카드뉴스, 키워드 그래프 중 어디를 먼저 찾을지 정하고 기업명, 키워드, 카드뉴스 제목을 입력하면 검색 결과 화면으로 이동합니다.',
  userFeeling: '메뉴를 먼저 고르지 않아도 떠오른 이슈를 바로 던질 수 있어 탐색 시작이 짧고 명확해집니다.',
  insights: [
    '검색 범위를 먼저 좁히면 같은 키워드도 보고 싶은 산출물 기준으로 빠르게 찾을 수 있습니다.',
    '검색창에 포커스가 없을 때 `/` 키로 바로 입력을 시작할 수 있습니다.',
  ],
  anchor: '상단 검색창',
  position: 'left-[560px] top-[98px]',
  arrow: 'left-12 -top-3 border-l border-t',
  highlight: 'left-[500px] top-[22px] h-[62px] w-[calc(100vw-980px)]',
};

export const peerPlusGlobalGuideSteps: ProductGuideStep[] = [
  {
    title: '글로벌 산업 필터',
    body: 'Peer+ 상단의 글로벌 산업 칩은 국내 Peer 비교 화면과 별도로 글로벌 IT 동향 화면을 여는 전환 버튼입니다. 개별 경쟁사 비교가 아니라 글로벌 6사와 외부 리서치에서 반복되는 산업 신호를 보는 모드로 이해하면 됩니다.',
    userFeeling: '국내 기업 비교에서 잠시 벗어나 산업 전체의 방향성을 먼저 확인할 수 있어, 이후 Peer 움직임을 더 넓은 맥락에서 읽게 됩니다.',
    insights: [
      '글로벌 산업은 SK AX와 특정 Peer의 직접 비교가 아니라 외부 시장 신호를 모아 보는 화면입니다.',
      '다시 개별 기업 칩을 누르면 Peer 비교 표와 SWOT 중심 화면으로 돌아갑니다.',
    ],
    anchor: '글로벌 산업 필터',
    position: 'right-[70px] top-[118px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[56px] top-[94px] h-[62px] w-[420px]',
  },
  {
    title: '글로벌 동향 개요',
    body: '글로벌 산업 화면은 엔비디아, 애플, 마이크로소프트, 구글, 아마존, 메타의 newsroom과 SPRi/BCG 리서치를 바탕으로 IT 트렌드와 사업 섹터 변화를 정리합니다. 특정 회사가 무엇을 했는지를 설명하기보다 산업 신호가 어디로 움직이는지를 먼저 봅니다.',
    userFeeling: '경쟁사 비교표를 읽기 전에 글로벌 시장의 큰 방향을 먼저 잡을 수 있어 개별 움직임의 의미가 더 선명해집니다.',
    insights: [
      '글로벌 6사와 리서치 자료에서 반복되는 키워드를 산업 신호로 묶어 봅니다.',
      '자동 갱신 기준과 최신 분석일을 함께 확인해 오늘 기준으로 볼 수 있는 트렌드인지 판단합니다.',
    ],
    anchor: '글로벌 동향 패널',
    position: 'left-[360px] top-[210px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[170px] h-[420px] w-[calc(100vw-390px)]',
  },
  {
    title: '분석 범위와 갱신 기준',
    body: '상단 헤더는 이 화면이 어떤 출처와 갱신 주기를 기준으로 만들어졌는지 알려줍니다. 최근 분석일, 핵심 트렌드 수, API 연동 여부를 확인해 현재 글로벌 산업 데이터의 신선도를 먼저 점검합니다.',
    userFeeling: '어떤 자료를 기준으로 한 해석인지 먼저 확인할 수 있어 이후 요약과 트렌드 카드를 더 신뢰하며 읽게 됩니다.',
    insights: [
      '분석 출처와 갱신 시간을 먼저 확인하면 오래된 흐름과 최신 신호를 구분하기 쉽습니다.',
      '새로고침으로 최신 연동 결과를 다시 불러올 수 있습니다.',
    ],
    anchor: '글로벌 분석 범위',
    position: 'left-[360px] top-[190px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[160px] h-[180px] w-[calc(100vw-390px)]',
  },
  {
    title: '글로벌 한 줄 요약',
    body: '핵심 요약 영역은 가장 강한 글로벌 신호를 한 문장으로 압축하고, 필요할 때 SK AX 관점의 시사점 초안을 함께 보여줍니다. 전체 카드 목록을 읽기 전에 오늘의 큰 방향을 잡는 시작점입니다.',
    userFeeling: '처음부터 카드 전체를 훑지 않아도 오늘 글로벌 IT 시장에서 가장 먼저 봐야 할 흐름이 빠르게 들어옵니다.',
    insights: [
      '신뢰도 배지를 함께 보며 요약의 강도를 확인할 수 있습니다.',
      '시사점 초안은 확정 결론이 아니라 이후 카드와 출처를 읽기 위한 출발점으로 활용합니다.',
    ],
    anchor: '글로벌 한 줄 요약',
    position: 'left-[360px] top-[360px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[315px] h-[260px] w-[calc(100vw-390px)]',
  },
  {
    title: '핵심 트렌드 카드',
    body: '핵심 트렌드 영역은 영향도 순으로 정렬된 산업 신호를 카드로 보여줍니다. 각 카드는 트렌드 요약, SK AX 시사점, 국내 Peer 대응 상태, 글로벌 주도 기업을 함께 담아 신호의 의미와 연결 대상을 한 번에 읽게 해줍니다.',
    userFeeling: '글로벌 흐름이 막연한 키워드로 끝나지 않고 사업 시사점과 국내 대응 현황까지 이어져 다음 분석 질문을 잡기 쉬워집니다.',
    insights: [
      '언급 수와 변화율을 보며 어떤 트렌드가 더 강하게 관측되는지 비교할 수 있습니다.',
      '국내 Peer 대응 칩은 글로벌 신호와 국내 움직임을 연결해 보는 보조 단서입니다.',
    ],
    anchor: '글로벌 핵심 트렌드',
    position: 'left-[360px] top-[620px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[560px] h-[420px] w-[calc(100vw-390px)]',
  },
  {
    title: '언급량 변화 감지',
    body: '트렌드 변화 영역은 이전 분석 대비 언급량이 크게 움직인 키워드를 따로 보여줍니다. 상승 신호는 가속 중인 주제, 하락 신호는 관심이 식는 주제로 보고 다음 모니터링 우선순위를 정합니다.',
    userFeeling: '현재 중요한 트렌드뿐 아니라 새로 커지는 신호와 식어가는 신호가 구분되어, 관찰 우선순위를 더 현실적으로 잡게 됩니다.',
    insights: [
      '변화폭이 큰 순서로 정렬되어 새롭게 부상하는 주제를 먼저 발견할 수 있습니다.',
      '언급량 변화는 핵심 트렌드 카드와 함께 읽을 때 산업 방향 전환을 더 빨리 감지하는 보조 지표가 됩니다.',
    ],
    anchor: '글로벌 언급량 변화',
    position: 'left-[360px] top-[760px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[700px] h-[300px] w-[calc(100vw-390px)]',
  },
];

export const mixerResultGuideSteps: ProductGuideStep[] = [
  {
    title: '믹서 결과 인사이트',
    body: '믹서 결과 화면의 첫 영역은 선택한 카드 묶음을 LLM 에이전트가 겹쳐 읽어 하나의 인사이트와 대응 방향으로 압축한 결과입니다. 여기서는 더 이상 카드를 고르는 단계가 아니라, 생성된 결론의 강도와 근거 흐름을 검토하는 단계입니다.',
    userFeeling: '내가 고른 카드들이 어떤 결론으로 합쳐졌는지 바로 보이기 때문에 생성 과정과 결과 판단이 분리되어 읽힙니다.',
    insights: [
      '상단에서 카드 조합 수, 신뢰도, 분석 방식을 먼저 확인할 수 있습니다.',
      '느낌표 버튼을 열면 이 인사이트가 어떤 추론 흐름으로 도출됐는지 따로 검증할 수 있습니다.',
    ],
    anchor: '믹서 결과 인사이트',
    position: 'left-[420px] top-[210px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[330px] top-[160px] h-[300px] w-[calc(100vw-840px)]',
  },
  {
    title: '상세 해석 보기',
    body: '상세 해석 영역은 카드 조합이 공통 패턴, 비교 포인트, 숨은 결론, 대응 방향으로 이어지는 과정을 단계별로 보여줍니다. 탭을 바꾸면 핵심 문장, 검증 근거, 참조 카드가 함께 바뀌어 결과 문장을 역추적할 수 있습니다.',
    userFeeling: '결론만 던져지는 것이 아니라 어떤 중간 판단을 거쳤는지 보이기 때문에 결과를 설명하거나 수정하기가 쉬워집니다.',
    insights: [
      '각 단계의 핵심 문장과 근거 문장을 분리해서 볼 수 있습니다.',
      '근거 카드 버튼을 열어 결과가 어떤 카드뉴스 맥락에서 나왔는지 바로 확인할 수 있습니다.',
    ],
    anchor: '믹서 상세 해석',
    position: 'left-[360px] top-[430px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[380px] h-[360px] w-[calc(100vw-390px)]',
  },
  {
    title: '분석 모드와 상세 검증',
    body: '분석 모드 영역은 빠른 실행과 정확 분석 중 어떤 방식으로 결과가 만들어졌는지, 어떤 검증 단계가 포함되거나 생략됐는지 보여줍니다. 정확 분석 결과에서는 섹션별 상세 검증을 열어 더 깊은 판단 근거를 볼 수 있습니다.',
    userFeeling: '결과의 길이와 깊이가 왜 달라졌는지 이해할 수 있어, 빠르게 볼 결과와 보고용으로 검증할 결과를 구분하게 됩니다.',
    insights: [
      '분석 방식에 따라 포함된 작업과 생략된 작업을 확인할 수 있습니다.',
      '정확 분석에서는 세부 검증 섹션을 오가며 결과 신뢰도를 더 촘촘히 점검할 수 있습니다.',
    ],
    anchor: '믹서 분석 모드',
    position: 'left-[360px] top-[620px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[560px] h-[300px] w-[calc(100vw-390px)]',
  },
  {
    title: '결과 신호 분포',
    body: '신호 강도 레이더는 결과 인사이트가 어떤 축에서 강하게 형성됐는지 보여줍니다. 축을 선택하면 점수, 판단 수위, 에이전트 해석, 연결된 근거 카드가 함께 표시되어 결과를 구조적으로 다시 검토할 수 있습니다.',
    userFeeling: '결과 문장을 한 번 읽고 끝내지 않고, 어떤 신호 축이 결론을 밀어 올렸는지 시각적으로 확인하게 됩니다.',
    insights: [
      '레이더 차트로 강한 신호와 약한 신호를 빠르게 비교할 수 있습니다.',
      '축별 근거 카드와 해석을 통해 결과가 어떤 카드 맥락에서 나왔는지 다시 연결할 수 있습니다.',
    ],
    anchor: '믹서 결과 신호 분포',
    position: 'left-[360px] top-[760px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[700px] h-[360px] w-[calc(100vw-760px)]',
  },
  {
    title: '다음 확인 포인트',
    body: '팔로업 영역은 현재 결과를 바탕으로 이어서 확인해야 할 질문과 초안 답변을 정리합니다. 결과 인사이트를 실제 검토나 보고로 넘기기 전에 어떤 추가 확인이 필요한지 점검하는 마지막 단계입니다.',
    userFeeling: '결과를 읽고 난 뒤 다음에 무엇을 더 확인해야 할지 바로 잡혀서 분석이 한 번 생성되고 끝나지 않습니다.',
    insights: [
      '질문과 답변을 함께 보며 후속 리서치 방향을 정할 수 있습니다.',
      '답변에 연결된 카드 근거를 열어 추가 확인이 필요한 부분을 빠르게 좁힐 수 있습니다.',
    ],
    anchor: '믹서 팔로업',
    position: 'left-[360px] top-[860px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[800px] h-[280px] w-[calc(100vw-390px)]',
  },
];

export const mixerHistoryGuideSteps: ProductGuideStep[] = [
  {
    title: '믹서 기록 날짜 필터',
    body: '믹서 기록 화면은 생성 화면이나 결과 화면과 분리된 누적 조회 공간입니다. 왼쪽에서 시작일과 종료일을 고르면 해당 기간에 저장된 실제 믹서 결과만 오른쪽 아카이브에 남습니다.',
    userFeeling: '현재 작업 중인 카드 선택 흐름을 방해하지 않고, 과거 결과만 별도로 찾아볼 수 있어 누적 관리가 더 정돈되어 느껴집니다.',
    insights: [
      '기간 범위만 바꿔 필요한 과거 결과를 다시 좁혀볼 수 있습니다.',
      '오늘 만든 결과와 이전 결과를 분리해서 확인할 수 있습니다.',
    ],
    anchor: '믹서 기록 날짜 필터',
    position: 'left-[330px] top-[180px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[315px] top-[132px] h-[340px] w-[300px]',
  },
  {
    title: '믹서 기록 아카이브',
    body: '오른쪽 아카이브는 기간 안에 포함된 믹서 결과를 날짜 단위로 다시 보여줍니다. 각 기록에서 분석 방식, 카드 수, 신뢰도를 확인하고 결과 열기 버튼으로 해당 결과 화면으로 돌아갈 수 있습니다.',
    userFeeling: '이전에 생성한 인사이트를 다시 찾고 열 수 있어 믹서 결과가 일회성 산출물로 사라지지 않습니다.',
    insights: [
      '저장된 결과의 제목과 한 줄 요약을 먼저 훑어볼 수 있습니다.',
      '결과 열기 버튼을 통해 과거 결과도 현재 결과 화면과 같은 구조로 다시 검토할 수 있습니다.',
    ],
    anchor: '믹서 기록 아카이브',
    position: 'left-[640px] top-[210px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[615px] top-[132px] h-[calc(100vh-220px)] w-[calc(100vw-700px)]',
  },
];

export const viewGuideMap: Record<string, ProductGuideStep[]> = {
  home: [
    searchGuideStep,
    {
      title: 'Today Insight',
      body: '홈의 첫 영역은 기준일별 Today Insight 리포트를 보여주는 진입 화면입니다. 핵심 문장, 주요 신호 카드, 선택한 신호의 AI 추론 과정, 근거, 달라진 점, 출처가 한 흐름으로 이어져 오늘 먼저 봐야 할 경쟁 신호를 SK AX 관점에서 정리합니다.',
      userFeeling: '기사와 수치를 하나씩 뒤지기 전에 오늘 무엇을 먼저 봐야 하는지가 먼저 잡혀서, 분석 시작점이 훨씬 또렷해집니다.',
      insights: [
        '오늘 어떤 신호가 가장 우선순위가 높은지 빠르게 정할 수 있습니다.',
        '핵심 결론뿐 아니라 AI 추론 과정과 근거를 같은 자리에서 함께 검증할 수 있습니다.',
      ],
      anchor: '메인 인사이트 영역',
      position: 'left-[360px] top-[176px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[136px] h-[440px] w-[calc(100vw-760px)]',
    },
    {
      title: '오늘의 요약 카드뉴스',
      body: '오른쪽 카드뉴스 큐는 오늘 우선 확인할 카드뉴스를 압축해 보여주는 영역입니다. 대표 카드를 열어 핵심 이슈를 먼저 확인하고, 아래 후보 리스트에서 다른 카드로 빠르게 전환할 수 있습니다.',
      userFeeling: '원문 기사 전체를 읽기 전에 오늘 중요한 카드부터 우선순위를 정할 수 있어 정보량이 많아도 부담이 덜합니다.',
      insights: [
        '대표 카드와 후보 리스트를 오가며 오늘 먼저 열어볼 뉴스를 고를 수 있습니다.',
        '상세 카드로 들어가면 요약, 시사점, 원문 링크까지 같은 흐름에서 확인할 수 있습니다.',
      ],
      anchor: '오늘의 요약 카드뉴스',
      position: 'right-[64px] top-[220px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] top-[150px] h-[410px] w-[390px]',
    },
    {
      title: '홈 차트 영역',
      body: '하단 차트는 섹터별 키워드 증감폭과 Peer사 주가 흐름을 번갈아 보는 보조 분석 레이어입니다. 좌우 전환 버튼으로 키워드 증감폭과 주가 증감률을 바꿔 보며, 뉴스에서 감지한 변화가 외부 검색 반응과 시장 반응으로 어떻게 이어지는지 확인합니다.',
      userFeeling: '정성 신호와 반응 데이터가 함께 보여서, 뉴스에서 본 변화가 실제 관심과 시장 움직임으로 어떻게 이어지는지 자연스럽게 연결됩니다.',
      insights: [
        '섹터 키워드 증감폭과 Peer사 주가 증감률을 같은 홈 화면에서 이어 볼 수 있습니다.',
        '검색 반응과 주가 흐름을 번갈아 보며 같은 이슈를 다른 관점으로 검증할 수 있습니다.',
      ],
      anchor: '홈 차트 영역',
      position: 'right-[84px] bottom-[92px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] bottom-[40px] h-[360px] w-[420px]',
    },
  ],
  briefings: [
    {
      title: '브리핑 기간 선택',
      body: '상단 기간 컨트롤에서 일간, 주간, 월간 브리핑 범위와 기준 날짜를 고릅니다. 같은 형식의 브리핑을 시점만 바꿔 다시 생성해 읽는 구조라 하루 변화와 주간·월간 누적 흐름을 같은 틀에서 비교하기 좋습니다.',
      userFeeling: '오늘 하루만이 아니라 지난 주와 월 단위 흐름까지 같은 구조로 이어 볼 수 있어 시장 맥락이 끊기지 않고 축적됩니다.',
      insights: [
        '단발성 기사인지 누적 흐름인지 판단하는 기준을 잡을 수 있습니다.',
        '같은 브리핑 포맷으로 시점만 바꿔 비교할 수 있어 해석 일관성이 높습니다.',
      ],
      anchor: '좌측 상단 기간 컨트롤',
      position: 'left-[330px] top-[112px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[96px] h-[64px] w-[430px]',
    },
    {
      title: '브리핑 본문',
      body: '브리핑 본문은 선택한 기간의 카드뉴스를 그대로 나열하지 않고 핵심 변화와 그 의미를 보고용 문장으로 다시 압축한 메인 리포트입니다. 상단 요약, 핵심 변화, 해석 흐름, 판단 근거가 이어져 기간 단위 흐름을 빠르게 읽게 해줍니다.',
      userFeeling: '기사와 숫자를 직접 엮지 않아도 회의나 보고 전에 바로 쓸 수 있는 문장 구조가 나와 있어 훨씬 빠르게 전체 맥락을 잡게 됩니다.',
      insights: [
        '브리핑 첫 문단만 읽어도 이번 기간에 무엇이 가장 크게 바뀌었는지 보고용 한 문장으로 정리할 수 있습니다.',
        '리드 문장과 요약 라인을 먼저 읽으면 세부 카드에 들어가기 전 전체 시장 톤과 변화 강도를 빠르게 잡을 수 있습니다.',
        '같은 페이지 안에서 변화 요약, 해석 흐름, 대응 포인트까지 이어져 회의 메모를 따로 다시 조립할 필요가 줄어듭니다.',
      ],
      anchor: '브리핑 본문',
      position: 'left-[420px] top-[258px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[210px] h-[420px] w-[calc(100vw-760px)]',
    },
    {
      title: '핵심 변화 카드',
      body: '브리핑의 핵심 변화 영역은 선택한 기간에 관측된 주요 시장 신호와 경쟁사 움직임을 카드 단위로 압축해 보여줍니다. 각 카드의 느낌표 버튼을 열면 어떤 근거 묶음으로 해당 변화가 뽑혔는지 확인할 수 있습니다.',
      userFeeling: '본문 전체를 다 읽기 전에 시장에서 실제로 무엇이 움직였는지 먼저 눈에 들어와서, 이후 해석 문장을 더 쉽게 따라가게 됩니다.',
      insights: [
        '시장 신호 카드에서는 수요, 기술, 투자 같은 외부 변화가 어디서 감지됐는지 빠르게 확인할 수 있습니다.',
        '경쟁사 움직임 카드에서는 어떤 기업이 어떤 메시지와 행동으로 존재감을 키우는지 바로 비교할 수 있습니다.',
        '추론 팝업을 열면 AI Agent가 어떤 기사 묶음과 패턴을 근거로 핵심 변화 축을 뽑았는지 함께 검증할 수 있습니다.',
      ],
      anchor: '브리핑 핵심 변화',
      position: 'left-[380px] top-[430px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[360px] h-[320px] w-[calc(100vw-820px)]',
    },
    {
      title: '해석 흐름',
      body: '핵심 변화 아래 해석 흐름 영역은 관찰된 변화가 어떤 평가축 이동으로 이어졌고, 그 결과 어떤 시사점이 나오는지를 단계별로 설명하는 구간입니다. 칩을 바꿔가며 AI Agent가 어떤 순서로 해석을 조립했는지 따라갈 수 있습니다.',
      userFeeling: '무슨 일이 있었는지를 넘어서 왜 이 변화가 중요한지까지 논리적으로 이어져서, 분석의 중심이 더 빨리 잡힙니다.',
      insights: [
        '관찰 → 평가축 이동 → 경쟁 구도 영향 → 전략 시사 흐름을 단계별로 따라가며 해석 논리를 복기할 수 있습니다.',
        '어느 단계에서 시장 신호가 전략 시사점으로 전환되는지 보여서 보고서 문장을 설명할 때 근거 흐름을 그대로 재사용하기 좋습니다.',
        '브리핑이 단순 요약이 아니라 구조화된 판단 결과물이라는 점을 더 분명하게 이해할 수 있습니다.',
      ],
      anchor: '브리핑 해석 흐름',
      position: 'left-[380px] top-[620px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[590px] h-[280px] w-[calc(100vw-820px)]',
    },
    {
      title: '공유·인쇄',
      body: '상단 공유·인쇄 버튼은 현재 선택한 기간과 브리핑 내용을 보고용 산출물로 넘기는 진입점입니다. 브리핑을 읽은 뒤 같은 화면에서 바로 전달 가능한 형태로 정리할 수 있습니다.',
      userFeeling: '읽기와 전달 동선이 분리되지 않아 브리핑 확인 후 바로 회의나 공유 흐름으로 이어가기 쉽습니다.',
      insights: [
        '현재 기간과 해석 구조를 유지한 채 공유·인쇄 미리보기로 이어집니다.',
        '브리핑을 개인 확인용 화면에서 팀 공유용 산출물로 빠르게 전환할 수 있습니다.',
      ],
      anchor: '브리핑 공유·인쇄',
      position: 'right-[58px] top-[132px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] top-[96px] h-[64px] w-[180px]',
    },
    {
      title: '판단 근거·출처',
      body: '오른쪽 근거 큐는 현재 브리핑 문장을 만드는 데 참조된 카드뉴스와 출처를 보여줍니다. 카드를 열면 요약, 시사점, 원문 링크까지 이어져 브리핑 문장을 실제 근거로 다시 검증할 수 있습니다.',
      userFeeling: '결론만 읽는 것이 아니라 어떤 카드와 출처가 그 문장을 받치고 있는지 바로 확인할 수 있어 더 안심하고 공유하게 됩니다.',
      insights: [
        '브리핑 문장이 어떤 카드 묶음에서 나왔는지 빠르게 추적할 수 있습니다.',
        '근거 카드를 열어 원문 출처와 세부 맥락을 같은 흐름에서 확인할 수 있습니다.',
      ],
      anchor: '근거 카드뉴스 큐',
      position: 'right-[58px] top-[300px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[210px] h-[520px] w-[360px]',
    },
  ],
  peerPlus: [
    {
      title: 'Peer 필터',
      body: '상단 필터 칩에서 전체 또는 개별 기업을 선택하면 아래 비교 표와 분석 섹션이 같은 기준으로 바뀝니다. 전체는 주요 Peer 전체 비교, 기업별은 SK AX와 선택 기업의 직접 비교라는 뜻입니다.',
      userFeeling: '시장 전체 구조를 보다가도 특정 경쟁사만 바로 좁혀볼 수 있어 비교 흐름이 자연스럽게 이어집니다.',
      insights: [
        '전체 모드와 기업별 모드를 같은 화면 구조 안에서 전환할 수 있습니다.',
        '필터 기준이 표, 비교 포인트, SWOT, 포지셔닝 영역에 일관되게 반영됩니다.',
      ],
      anchor: 'Peer+ 상단',
      position: 'right-[70px] top-[118px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[56px] top-[94px] h-[62px] w-[420px]',
    },
    {
      title: 'Peer 한눈 비교',
      body: '상단 표는 SK AX와 주요 Peer의 매출, 영업이익, 영업이익률, 사업 키워드, 기술 키워드를 같은 순서로 놓고 비교하는 영역입니다. 전체 모드에서는 시장 비교, 기업별 모드에서는 SK AX와 선택 기업만 남겨 읽기 쉽게 압축됩니다.',
      userFeeling: '공시 수치와 핵심 키워드를 한 표에서 같이 봐서 긴 자료를 읽기 전에 전체 경쟁 구도를 빠르게 파악하게 됩니다.',
      insights: [
        '누가 규모와 수익성에서 우위인지 한 번에 비교할 수 있습니다.',
        '재무 값과 사업·기술 키워드를 같이 읽어 숫자와 메시지의 연결을 잡을 수 있습니다.',
      ],
      anchor: 'Peer 한눈 비교 표',
      position: 'left-[360px] top-[230px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[170px] h-[220px] w-[calc(100vw-390px)]',
    },
    {
      title: '핵심 비교 포인트',
      body: '비교 요약 영역은 Peer별 공개 신호를 사업, 기술, 리스크 축으로 나눠 비교 문장 형태로 보여줍니다. 정보 아이콘을 열면 비교 에이전트가 어떤 근거를 교차 검토해 공개 신호의 차이를 읽었는지 확인할 수 있습니다.',
      userFeeling: '복잡한 비교 항목이 축별 문장으로 정리되어 있어 보고나 논의 전에 경쟁 구도의 차이를 빠르게 파악하게 됩니다.',
      insights: [
        '사업 신호, 기술 신호, 리스크 축으로 나뉘어 있어 Peer별 강조점이 어디에 있는지 비교할 수 있습니다.',
        '선택 기업이 어떤 축에서 더 강하게 움직이는지 보고 시장 내 포지션 차이를 빠르게 잡을 수 있습니다.',
        '근거 팝업으로 비교 문장이 어떤 공시, 기사, 카드 묶음에서 나왔는지 역추적할 수 있습니다.',
      ],
      anchor: 'Peer 비교 시사점',
      position: 'left-[360px] top-[430px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[380px] h-[300px] w-[calc(100vw-390px)]',
    },
    {
      title: 'SWOT 분석',
      body: 'SWOT 보드는 같은 비교 결과를 전략 해석 관점으로 다시 정리한 영역입니다. 강점·약점·기회·위협을 각각 읽고, 정보 아이콘을 통해 전략 에이전트가 어떤 공개 신호를 근거로 네 가지 축을 구성했는지 이어서 볼 수 있습니다.',
      userFeeling: '실무 비교와 전략 해석이 분리되어 있어 현재 경쟁사의 위치와 더 길게 볼 관찰 포인트를 자연스럽게 나눠보게 됩니다.',
      insights: [
        '같은 비교 데이터를 강점·약점·기회·위협으로 다시 분해해 중장기 전략 논의용 프레임으로 전환할 수 있습니다.',
        '특정 경쟁사를 단순 비교하는 수준을 넘어서 공개 신호가 어떤 전략적 관찰 축으로 묶이는지 확인할 수 있습니다.',
        'SWOT 팝업으로 전략 에이전트가 어떤 카드와 시장 신호를 근거로 각 축을 구성했는지 확인할 수 있습니다.',
      ],
      anchor: 'Peer 비교 시사점',
      position: 'right-[62px] top-[430px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[380px] h-[300px] w-[420px]',
    },
    {
      title: '사업 규모 × 매출 성장률',
      body: '전체 모드에서만 보이는 포지셔닝 그래프는 각 Peer를 사업 규모와 매출 성장률 두 축 위에 올려 시장 내 위치를 한눈에 보여줍니다. 표에서 본 숫자를 절대값이 아니라 상대 위치로 다시 읽게 해주는 시각화입니다.',
      userFeeling: '누가 크고 누가 빠르게 커지는지 좌표로 바로 보여서, 숫자를 하나씩 비교할 때보다 시장 판세가 훨씬 빠르게 들어옵니다.',
      insights: [
        '상단 표에서 규모가 큰 기업과 성장률이 높은 기업이 실제로 어떤 사분면에 몰려 있는지 바로 확인할 수 있습니다.',
        'SK AX가 시장 평균 대비 어느 위치에 있는지 보고, 추격 대상과 차별화 대상 기업을 빠르게 나눌 수 있습니다.',
        '필터가 전체일 때만 노출되므로 전체 시장 구조를 읽는 전용 단계로 활용하기 좋습니다.',
      ],
      anchor: 'Peer 포지셔닝',
      position: 'left-[360px] top-[760px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[700px] h-[360px] w-[calc(100vw-760px)]',
    },
  ],
  issues: [
    {
      title: '카드뉴스 필터',
      body: '상단 필터 영역에서는 Peer사, 섹터, 날짜, 키워드, 북마크 여부를 조합해 카드 목록을 좁혀 봅니다. 조건을 바꾸면 아래 카드뉴스 그리드가 즉시 다시 계산되어 필요한 카드만 남습니다.',
      userFeeling: '원하는 산업과 기업 뉴스만 빠르게 골라볼 수 있어 탐색 피로가 줄고, 지금 필요한 카드에 더 집중하게 됩니다.',
      insights: [
        '기업·섹터·날짜·키워드 기준으로 카드뉴스를 즉시 다시 좁힐 수 있습니다.',
        '북마크 카드만 따로 모아 다시 검토하는 용도로도 활용할 수 있습니다.',
      ],
      anchor: '카드뉴스 필터 영역',
      position: 'left-[330px] top-[142px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[112px] h-[92px] w-[calc(100vw-390px)]',
    },
    {
      title: '카드뉴스 그리드',
      body: '카드뉴스 목록은 커버, 날짜, 카테고리, Peer사 정보를 한 장에 압축해 보여주는 탐색 그리드입니다. 먼저 넓게 훑고 필요한 카드만 열어 상세 오버레이에서 요약, 시사점, 원문 링크까지 이어서 확인하는 구조입니다.',
      userFeeling: '긴 기사 원문으로 바로 들어가기 전에 핵심 정보만 넓게 스캔할 수 있어 탐색 속도가 훨씬 빨라집니다.',
      insights: [
        '산업과 경쟁사 관련 이슈를 카드 단위로 넓게 비교할 수 있습니다.',
        '제목과 메타 정보만으로도 어떤 주제가 반복되는지 감을 잡기 쉽습니다.',
      ],
      anchor: '카드뉴스 목록',
      position: 'left-[360px] top-[300px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[235px] h-[calc(100vh-330px)] w-[calc(100vw-390px)]',
    },
  ],
  mixer: [
    {
      title: '믹서 입력 조합',
      body: '믹서 작업 화면의 첫 단계에서는 Peer, 고객사, 산업, 키워드를 칩으로 조합합니다. 여기서 고른 입력 축이 어떤 카드가 후보로 남는지와 이후 결과가 어떤 관점으로 묶일지를 결정합니다.',
      userFeeling: '내가 중요하다고 보는 시장 축으로 직접 분석 조건을 설계하는 느낌이 들어, 단순 조회보다 훨씬 주도적으로 화면을 다루게 됩니다.',
      insights: [
        '같은 카드뉴스도 어떤 입력 조합을 먼저 고르느냐에 따라 전혀 다른 결과가 나옵니다.',
        '입력 단계 자체가 어떤 시나리오를 실험할지 가설을 세우는 출발점이 됩니다.',
      ],
      anchor: '믹서 선택 패널',
      position: 'left-[330px] top-[160px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[108px] h-[180px] w-[calc(100vw-700px)]',
    },
    {
      title: '카드뉴스 후보 선택',
      body: '중앙 카드 그리드에서는 입력 조건에 맞는 카드뉴스 후보를 실제 인풋으로 선택합니다. 선택한 카드와 북마크한 카드가 이후 결과 인사이트와 근거 카드뉴스에 다시 연결되므로, 결과의 출발점이 어디였는지가 분명하게 남습니다.',
      userFeeling: '내가 직접 고른 카드가 결과의 근거가 된다는 점이 명확해서, 이후에 나오는 인사이트를 더 설명 가능하게 받아들이게 됩니다.',
      insights: [
        '필터와 카드 선택이 함께 작동해 어떤 카드 묶음을 실험할지 설계할 수 있습니다.',
        '선택 카드가 결과 화면의 근거 카드뉴스와 그대로 이어집니다.',
      ],
      anchor: '카드뉴스 후보/북마크',
      position: 'left-[360px] top-[360px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[290px] h-[calc(100vh-360px)] w-[calc(100vw-430px)]',
    },
    {
      title: '입력 비율과 최근 결과',
      body: '오른쪽 패널에서는 현재 선택한 Peer와 카드 유형 비율을 도넛 차트로 보여줍니다. 한쪽 입력으로 너무 치우치지 않았는지 빠르게 점검하고, 아래 최근 결과 영역을 통해 믹서가 일회성 실행이 아니라 누적될 수 있는 구조라는 점을 이해하게 됩니다.',
      userFeeling: '결과를 만들기 전에 입력 균형을 점검할 수 있어 분석 과정이 더 안정적으로 느껴집니다.',
      insights: [
        '현재 입력 구성이 어느 쪽으로 기울었는지 바로 확인할 수 있습니다.',
        '최근 결과 영역을 통해 추후 누적 관리 흐름을 미리 이해할 수 있습니다.',
      ],
      anchor: '입력 비율 차트',
      position: 'right-[70px] top-[320px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[56px] top-[250px] h-[430px] w-[340px]',
    },
  ],
  keywordGraph: [
    {
      title: '키워드 필터와 보기 전환',
      body: '상단 컨트롤에서는 기업, AX, 보안, 인프라, 수주 같은 카테고리로 그래프를 좁히고 확대·축소와 전체화면을 조절합니다. 같은 키워드 맵을 어떤 초점으로 볼지 먼저 정하는 영역입니다.',
      userFeeling: '복잡한 관계망을 그대로 다 보지 않고 궁금한 축만 남겨 볼 수 있어 분석 초점이 훨씬 또렷해집니다.',
      insights: [
        '특정 기업군이나 주제 축만 남겨 연결 구조를 선택적으로 확인할 수 있습니다.',
        '확대·축소와 전체화면 전환으로 복잡한 관계망을 더 읽기 쉬운 방식으로 바꿔 볼 수 있습니다.',
      ],
      anchor: '상단 컨트롤',
      position: 'right-[58px] top-[142px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] top-[104px] h-[92px] w-[520px]',
    },
    {
      title: '키워드 맵과 관련 카드뉴스',
      body: '그래프 본문에서는 기업, 산업, 세부 키워드가 관계망으로 펼쳐지고, 노드를 클릭하면 관련 카드뉴스 오버레이가 열립니다. 즉 관계 구조를 보고 바로 기사 근거로 내려가는 흐름이 같은 화면 안에서 이어집니다.',
      userFeeling: '시각화가 추상적인 그림에서 끝나지 않고 실제 카드뉴스로 바로 연결되어, 관계망이 근거 탐색 도구처럼 느껴집니다.',
      insights: [
        '현재 시장에서 중심이 되는 키워드와 연결 강도를 직관적으로 확인할 수 있습니다.',
        '특정 키워드가 어떤 기업, 어떤 주제와 동시에 묶여 있는지 관계 구조로 바로 파악할 수 있습니다.',
        '노드를 누르면 관련 카드뉴스까지 이어져 추상적인 관계를 실제 기사 맥락으로 곧바로 검증할 수 있습니다.',
      ],
      anchor: '2D 그래프 영역',
      position: 'left-[380px] top-[250px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[160px] h-[calc(100vh-240px)] w-[calc(100vw-680px)]',
    },
  ],
  settings: [
    {
      title: '설정 탭',
      body: '설정 화면은 회원 정보, 접속 로그, 알림 설정 세 가지 탭으로 구성됩니다. 왼쪽 탭에서 범주를 바꾸고, 오른쪽 본문에서 해당 영역의 입력값을 수정하거나 이력을 확인하는 구조입니다.',
      userFeeling: '프로필과 알림, 접속 이력을 한곳에서 나눠 관리할 수 있어 서비스가 더 개인화되고 관리 가능하게 느껴집니다.',
      insights: [
        '브리핑과 이벤트 알림을 내 업무 리듬에 맞게 조정할 수 있습니다.',
        '접속 로그를 통해 보안과 사용 이력을 함께 점검할 수 있습니다.',
      ],
      anchor: '설정 탭',
      position: 'left-[340px] top-[230px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[185px] h-[220px] w-[300px]',
    },
  ],
};

export const commonGuideSteps: ProductGuideStep[] = [
  searchGuideStep,
  {
    title: '업데이트 기준 시각',
    body: '상단 우측의 업데이트 표시는 현재 화면 데이터가 어느 시점 기준으로 갱신됐는지 보여줍니다. 브리핑, 카드뉴스, Peer+처럼 갱신 주기가 다른 화면을 오갈 때 해석 기준 시점을 맞추는 역할을 합니다.',
    userFeeling: '지금 보고 있는 숫자와 요약이 어느 시점까지 반영됐는지 먼저 확인할 수 있어 판단 기준이 더 분명해집니다.',
    insights: [
      '화면별 최신 반영 시점을 확인해 오래된 결과와 새 결과를 구분할 수 있습니다.',
      '보고나 회의에서 자료 기준 시간을 설명해야 할 때 빠르게 확인할 수 있습니다.',
    ],
    anchor: '업데이트 기준 시각',
    position: 'right-[56px] top-[126px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[168px] top-[92px] h-[64px] w-[220px]',
  },
  {
    title: '알림 센터',
    body: '벨 아이콘은 새로 들어온 중요 알림을 여는 버튼입니다. 알림 패널에서는 안 읽은 변화, 키워드 매칭, 이동 가능한 대상 화면을 확인하고 필요한 항목을 눌러 관련 화면으로 바로 넘어갈 수 있습니다.',
    userFeeling: '새로운 변화가 생겼을 때 어디부터 확인해야 하는지 상단에서 바로 알 수 있어 흐름을 놓치지 않습니다.',
    insights: [
      '안 읽은 알림 수와 중요 알림을 빠르게 확인할 수 있습니다.',
      '알림 항목을 누르면 관련 카드뉴스, 브리핑, 알림 목록으로 이어져 후속 확인이 짧아집니다.',
    ],
    anchor: '알림 센터',
    position: 'right-[56px] top-[126px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[128px] top-[132px] h-[64px] w-[64px]',
  },
  {
    title: '도움말 버튼',
    body: '물음표 버튼은 지금 보고 있는 화면의 튜토리얼을 다시 여는 진입점입니다. 홈에서는 상단바와 주요 공통 동선을 함께 훑고, 각 분석 화면에서는 해당 화면의 핵심 영역을 순서대로 안내합니다.',
    userFeeling: '기능이 헷갈릴 때 다른 문서로 나가지 않고 같은 화면 위에서 설명을 다시 확인할 수 있습니다.',
    insights: [
      '현재 화면에서 먼저 봐야 할 영역과 다음 이동 흐름을 다시 확인할 수 있습니다.',
      '화면 구조가 바뀌어도 실제 요소 위치를 따라 하이라이트가 다시 잡힙니다.',
    ],
    anchor: '도움말 버튼',
    position: 'right-[56px] top-[170px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[96px] top-[132px] h-[64px] w-[64px]',
  },
  {
    title: '프로필과 설정',
    body: '프로필 버튼은 설정 화면으로 이동하는 상단 진입점입니다. 회원 정보, 접속 로그, 알림 설정, 글자 크기 같은 개인 환경을 한곳에서 확인하고 조정합니다.',
    userFeeling: '개인화와 계정 관리가 상단의 같은 위치에 모여 있어 필요한 조정을 빠르게 끝낼 수 있습니다.',
    insights: [
      '알림 기준과 화면 읽기 환경을 업무 방식에 맞게 바꿀 수 있습니다.',
      '접속 로그와 계정 정보를 설정 화면에서 함께 점검할 수 있습니다.',
    ],
    anchor: '프로필·설정',
    position: 'right-[32px] top-[170px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[32px] top-[132px] h-[64px] w-[64px]',
  },
  {
    title: '사이드바 이동',
    body: '좌측 사이드바에서는 홈, 브리핑, Peer+, 카드뉴스, 믹서, 키워드 그래프 같은 주요 분석 화면으로 이동합니다. 현재 보고 있는 메뉴가 강조되어 있어 지금 어느 분석 단계에 있는지 바로 파악할 수 있습니다.',
    userFeeling: '여러 기능을 오가더라도 현재 위치를 잃지 않고 원하는 분석 화면으로 빠르게 전환할 수 있어 흐름이 안정적으로 느껴집니다.',
    insights: [
      '핵심 분석 화면을 같은 정보 흐름 안에서 오가며 비교할 수 있습니다.',
      '현재 보고 있는 화면과 다음 분석 단계의 연결 맥락을 유지할 수 있습니다.',
    ],
    anchor: '사이드바 메뉴',
    position: 'left-[260px] top-[260px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[12px] top-[84px] h-[calc(100vh-140px)] w-[220px]',
  },
  {
    title: 'AXIS AI 챗봇',
    body: '우측 하단 AI 챗봇은 현재 화면 내용을 질문형으로 다시 탐색하는 보조 도구입니다. 보고 있는 카드뉴스, 비교 화면, 브리핑 결과를 바탕으로 재설명, 요약, 후속 질문을 이어갈 수 있습니다.',
    userFeeling: '정적인 화면을 읽는 데서 멈추지 않고 필요한 내용을 바로 질문해 다시 설명받을 수 있어 이해 속도가 빨라집니다.',
    insights: [
      '복잡한 비교 결과나 카드 흐름을 대화형으로 다시 정리할 수 있습니다.',
      '현재 화면 내용을 바탕으로 보고용 문장이나 후속 질문을 빠르게 뽑아볼 수 있습니다.',
    ],
    anchor: 'AI 챗봇',
    position: 'right-[86px] bottom-[120px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[48px] bottom-[48px] h-[72px] w-[72px]',
  },
];

export const guideTargetByAnchor: Record<string, string> = {
  '상단 검색창': 'global-search',
  '업데이트 기준 시각': 'topnav-update',
  '알림 센터': 'topnav-alerts',
  '도움말 버튼': 'topnav-help',
  '프로필·설정': 'topnav-profile',
  '사이드바 메뉴': 'sidebar-nav',
  'AI 챗봇': 'ai-chat',
  '메인 인사이트 영역': 'home-insight',
  '오늘의 요약 카드뉴스': 'home-summary',
  '홈 차트 영역': 'home-charts',
  '좌측 상단 기간 컨트롤': 'briefing-period',
  '브리핑 본문': 'briefing-main',
  '브리핑 핵심 변화': 'briefing-focus',
  '브리핑 해석 흐름': 'insight-flow',
  '브리핑 공유·인쇄': 'briefing-share-print',
  '근거 카드뉴스 큐': 'briefing-evidence',
  'Peer+ 상단': 'peer-selector',
  '글로벌 산업 필터': 'peer-selector',
  '글로벌 동향 패널': 'peer-global-trends',
  '글로벌 분석 범위': 'global-trends-header',
  '글로벌 한 줄 요약': 'global-trends-summary',
  '글로벌 핵심 트렌드': 'global-trends-key-trends',
  '글로벌 언급량 변화': 'global-trends-shifts',
  'Peer 한눈 비교 표': 'peer-overview',
  'Peer 비교 시사점': 'peer-insight',
  'Peer 포지셔닝': 'peer-positioning',
  '카드뉴스 필터 영역': 'cardnews-filter',
  '카드뉴스 목록': 'cardnews-grid',
  '믹서 선택 패널': 'mixer-input',
  '카드뉴스 후보/북마크': 'mixer-candidates',
  '입력 비율 차트': 'mixer-ratio',
  '믹서 결과 인사이트': 'mixer-result-headline',
  '믹서 상세 해석': 'mixer-result-steps',
  '믹서 분석 모드': 'mixer-result-depth',
  '믹서 결과 신호 분포': 'mixer-signal-map',
  '믹서 팔로업': 'mixer-follow-up',
  '믹서 기록 날짜 필터': 'mixer-history-filter',
  '믹서 기록 아카이브': 'mixer-history-archive',
  '믹서 기록 스크롤 영역': 'mixer-history-archive',
  '키워드 필터': 'keyword-filter',
  '2D 그래프 영역': 'keyword-map',
  '노드 선택 결과': 'keyword-map',
  '상단 컨트롤': 'keyword-controls',
  '설정 탭': 'settings-tabs',
};
