export type ProductGuideStep = {
  title: string;
  body: string;
  userFeeling: string;
  insights: string[];
  anchor: string;
  position: string;
  arrow: string;
  highlight: string;
};

const searchGuideStep: ProductGuideStep = {
  title: '통합 검색',
  body: '상단 검색창은 AXIS 전체의 가장 빠른 진입점입니다. 기업명, 카드뉴스 제목, 핵심 키워드를 입력하면 Peer+, 카드뉴스, 관련 분석 화면으로 바로 이어져 메뉴를 여러 번 옮기지 않아도 원하는 맥락으로 바로 들어갈 수 있습니다.',
  userFeeling: '찾고 싶은 이슈가 이미 있을 때 화면을 돌아다니지 않고 곧바로 목적지로 이동할 수 있어 탐색이 훨씬 짧고 선명하게 느껴집니다.',
  insights: [
    '특정 경쟁사 중심 비교나 관련 카드뉴스 탐색을 한 번에 시작할 수 있습니다.',
    '반복 키워드가 실제로 어느 화면과 기사에 연결되는지 빠르게 좁혀볼 수 있습니다.',
  ],
  anchor: '상단 검색창',
  position: 'left-[560px] top-[98px]',
  arrow: 'left-12 -top-3 border-l border-t',
  highlight: 'left-[500px] top-[22px] h-[62px] w-[calc(100vw-980px)]',
};

export const viewGuideMap: Record<string, ProductGuideStep[]> = {
  home: [
    searchGuideStep,
    {
      title: 'Today Insight',
      body: '홈의 첫 영역은 오늘 가장 먼저 읽어야 할 경쟁 신호를 SK AX 관점에서 압축한 진입 화면입니다. 상단 핵심 문장, 주요 신호 카드, 그리고 아래 AI 추론 과정·근거·달라진 점이 한 흐름으로 이어져 오늘의 판단 프레임을 빠르게 세우게 해줍니다.',
      userFeeling: '기사와 수치를 하나씩 보기 전에 오늘 무엇을 먼저 읽어야 하는지가 먼저 잡혀서, 분석 시작점이 훨씬 또렷해집니다.',
      insights: [
        '오늘 어떤 신호가 가장 우선순위가 높은지 빠르게 정할 수 있습니다.',
        '핵심 결론뿐 아니라 AI 추론 과정과 근거를 같은 자리에서 함께 검증할 수 있습니다.',
      ],
      anchor: '메인 인사이트 영역',
      position: 'left-[360px] top-[176px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[136px] h-[440px] w-[calc(100vw-760px)]',
    },
    {
      title: '오늘의 요약 카드뉴스',
      body: '오른쪽 카드뉴스 큐는 오늘 우선 확인해야 할 카드만 압축해 보여주는 영역입니다. 대표 카드로 핵심 이슈를 먼저 보고, 아래 리스트에서 다른 후보 카드로 빠르게 전환한 뒤 상세 카드뉴스로 바로 들어갈 수 있습니다.',
      userFeeling: '원문 기사 전체를 읽기 전에 오늘 중요한 카드부터 우선순위를 정할 수 있어 정보량이 많아도 부담이 덜합니다.',
      insights: [
        '대표 카드와 후보 리스트를 오가며 오늘 먼저 열어볼 뉴스를 고를 수 있습니다.',
        '상세 카드로 들어가면 요약, 시사점, 원문 링크까지 같은 흐름에서 확인할 수 있습니다.',
      ],
      anchor: '오늘의 요약 카드뉴스',
      position: 'right-[64px] top-[220px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] top-[150px] h-[410px] w-[390px]',
    },
    {
      title: '홈 차트 영역',
      body: '하단 차트는 키워드 검색지수 변화와 Peer사 주가 흐름을 번갈아 보는 보조 분석 레이어입니다. 토글을 바꿔 반응 신호와 시장 반응을 함께 읽고, 검색지수 그래프에서는 튀는 포인트를 눌러 원인과 SK AX 해석까지 바로 확인할 수 있습니다.',
      userFeeling: '정성 신호와 반응 데이터가 함께 보여서, 뉴스에서 본 변화가 실제 관심과 시장 움직임으로 어떻게 이어지는지 자연스럽게 연결됩니다.',
      insights: [
        '키워드 급등 원인과 SK AX 포인트를 차트 안에서 바로 읽을 수 있습니다.',
        '검색 반응과 주가 흐름을 번갈아 보며 같은 이슈를 다른 관점으로 검증할 수 있습니다.',
      ],
      anchor: '홈 차트 영역',
      position: 'right-[84px] bottom-[92px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] bottom-[40px] h-[360px] w-[420px]',
    },
  ],
  briefings: [
    {
      title: '브리핑 기간 선택',
      body: '상단 기간 컨트롤에서 일간, 주간, 월간 브리핑 범위와 기준 날짜를 고릅니다. 같은 형식의 브리핑을 시점만 바꿔 다시 생성해 읽는 구조라 하루 변화와 주간·월간 누적 흐름을 같은 틀에서 비교하기 좋습니다.',
      userFeeling: '오늘 하루만이 아니라 지난 주와 월 단위 흐름까지 같은 구조로 이어 볼 수 있어 시장 맥락이 끊기지 않고 축적됩니다.',
      insights: [
        '단발성 기사인지 누적 흐름인지 판단하는 기준을 잡을 수 있습니다.',
        '같은 브리핑 포맷으로 시점만 바꿔 비교할 수 있어 해석 일관성이 높습니다.',
      ],
      anchor: '좌측 상단 기간 컨트롤',
      position: 'left-[330px] top-[112px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[96px] h-[64px] w-[430px]',
    },
    {
      title: '브리핑 본문',
      body: '브리핑 본문은 선택한 기간의 카드뉴스를 그대로 나열하지 않고 핵심 변화와 그 의미를 보고용 문장으로 다시 압축한 메인 리포트입니다. 상단 리드, 오늘의 핵심 변화, 해석 흐름, 시장 해석과 SK AX 시사점 순서로 읽게 됩니다.',
      userFeeling: '기사와 숫자를 직접 엮지 않아도 회의나 보고 전에 바로 쓸 수 있는 문장 구조가 나와 있어 훨씬 빠르게 전체 맥락을 잡게 됩니다.',
      insights: [
        '브리핑 첫 문단만 읽어도 이번 기간에 무엇이 가장 크게 바뀌었는지 보고용 한 문장으로 정리할 수 있습니다.',
        '리드 문장과 요약 라인을 먼저 읽으면 세부 카드에 들어가기 전 전체 시장 톤과 변화 강도를 빠르게 잡을 수 있습니다.',
        '같은 페이지 안에서 변화 요약, 해석 흐름, 대응 포인트까지 이어져 회의 메모를 따로 다시 조립할 필요가 줄어듭니다.',
      ],
      anchor: '브리핑 본문',
      position: 'left-[420px] top-[258px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[210px] h-[420px] w-[calc(100vw-760px)]',
    },
    {
      title: '핵심 변화 카드',
      body: '브리핑 상단의 오늘의 핵심 변화 영역은 시장 신호와 경쟁사 움직임을 나눠 보여주며, 이번 기간에 어떤 변화가 실제로 관측됐는지 먼저 압축해서 보여줍니다. 메인 카드로 중심 변화를 읽고, 아래 세부 카드에서 신호별 이유와 의미를 빠르게 이어 확인하는 구조입니다.',
      userFeeling: '본문 전체를 다 읽기 전에 시장에서 실제로 무엇이 움직였는지 먼저 눈에 들어와서, 이후 해석 문장을 더 쉽게 따라가게 됩니다.',
      insights: [
        '시장 신호 카드에서는 수요, 기술, 투자 같은 외부 변화가 어디서 감지됐는지 빠르게 확인할 수 있습니다.',
        '경쟁사 움직임 카드에서는 어떤 기업이 어떤 메시지와 행동으로 존재감을 키우는지 바로 비교할 수 있습니다.',
        '섹션 단위 추론 팝업을 열면 AI Agent가 어떤 기사 묶음과 패턴을 근거로 핵심 변화 축을 뽑았는지 함께 검증할 수 있습니다.',
      ],
      anchor: '브리핑 핵심 변화',
      position: 'left-[380px] top-[430px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[360px] h-[320px] w-[calc(100vw-820px)]',
    },
    {
      title: '해석 흐름',
      body: '핵심 변화 아래 해석 흐름 영역은 관찰된 변화가 어떤 평가축 이동으로 이어졌고, 그 결과 어떤 시사점이 나오는지를 단계별로 설명하는 구간입니다. 칩을 바꿔가며 AI Agent가 어떤 순서로 해석을 조립했는지 따라갈 수 있습니다.',
      userFeeling: '무슨 일이 있었는지를 넘어서 왜 이 변화가 중요한지까지 논리적으로 이어져서, 분석의 중심이 더 빨리 잡힙니다.',
      insights: [
        '관찰 → 평가축 이동 → 경쟁 구도 영향 → 전략 시사 흐름을 단계별로 따라가며 해석 논리를 복기할 수 있습니다.',
        '어느 단계에서 시장 신호가 전략 시사점으로 전환되는지 보여서 보고서 문장을 설명할 때 근거 흐름을 그대로 재사용하기 좋습니다.',
        '브리핑이 단순 요약이 아니라 구조화된 판단 결과물이라는 점을 더 분명하게 이해할 수 있습니다.',
      ],
      anchor: '브리핑 해석 흐름',
      position: 'left-[380px] top-[620px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[590px] h-[280px] w-[calc(100vw-820px)]',
    },
    {
      title: '시장 해석과 SK AX 시사점',
      body: '하단 두 섹션은 같은 기간의 카드 묶음을 시장 해석과 SK AX 대응 방향으로 나눠 읽는 영역입니다. 각 섹션의 느낌표를 열면 AI Agent가 어떤 공개 신호를 교차 검토해 해당 문장을 만들었는지 reasoning과 근거 카드까지 함께 확인할 수 있습니다.',
      userFeeling: '사실 설명과 전략 해석이 분리되어 있어 지금 당장 보고에 쓸 문장과 내부 대응 포인트를 자연스럽게 구분하게 됩니다.',
      insights: [
        '시장 해석 포인트에서는 경쟁 구도와 수요 이동을 외부 시각으로 정리하고, SK AX 시사점에서는 바로 내부 대응 문장으로 이어 읽을 수 있습니다.',
        '보고용 문장과 실행용 문장이 분리되어 있어 대외 설명과 내부 액션 포인트를 섞지 않고 정리할 수 있습니다.',
        '각 섹션별 reasoning 팝업으로 AI Agent가 어떤 카드와 신호를 묶어 해당 문장을 만들었는지 확인할 수 있습니다.',
      ],
      anchor: '브리핑 해석 섹션',
      position: 'left-[380px] top-[900px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[860px] h-[360px] w-[calc(100vw-820px)]',
    },
    {
      title: '근거 카드뉴스와 공유',
      body: '오른쪽 근거 카드 큐는 현재 브리핑 문장을 만드는 데 사용된 카드뉴스 목록이고, 상단 공유·인쇄 버튼은 현재 브리핑을 보고용 산출물로 바로 넘기는 진입점입니다. 브리핑을 읽고 검증하고 전달하는 흐름이 같은 화면 안에서 끝납니다.',
      userFeeling: '결론만 읽는 것이 아니라 근거 기사와 전달 수단까지 바로 이어져서, 개인 메모가 아니라 실제 협업 결과물처럼 느껴집니다.',
      insights: [
        '브리핑 문장이 어떤 카드 묶음에서 나왔는지 빠르게 추적할 수 있습니다.',
        '현재 선택한 기간과 해석 구조를 그대로 보존한 채 공유·인쇄할 수 있습니다.',
      ],
      anchor: '근거 카드뉴스 큐',
      position: 'right-[58px] top-[300px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[210px] h-[520px] w-[360px]',
    },
  ],
  peerPlus: [
    {
      title: 'Peer 필터',
      body: '상단 필터 칩에서 전체 또는 개별 기업을 선택하면 아래 표와 비교 섹션, 레이더가 모두 같은 기준으로 즉시 바뀝니다. 전체는 시장 전체 비교, 기업별은 SK AX와 선택 기업의 직접 비교라는 뜻입니다.',
      userFeeling: '시장 전체 구조를 보다가도 특정 경쟁사만 바로 좁혀볼 수 있어 비교 흐름이 자연스럽게 이어집니다.',
      insights: [
        '전체 모드와 기업별 모드를 같은 화면 구조 안에서 전환할 수 있습니다.',
        '필터 기준이 아래 모든 비교 컴포넌트에 동시에 반영되어 해석이 흔들리지 않습니다.',
      ],
      anchor: 'Peer+ 상단',
      position: 'right-[70px] top-[118px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[56px] top-[94px] h-[62px] w-[420px]',
    },
    {
      title: 'Peer 한눈 비교',
      body: '상단 표는 SK AX와 주요 Peer의 매출, 영업이익, 영업이익률, AX 비중, 수주 수, 핵심 키워드를 같은 순서로 놓고 비교하는 영역입니다. 전체 모드에서는 시장 비교, 기업별 모드에서는 SK AX와 선택 기업만 남겨 읽기 쉽게 압축됩니다.',
      userFeeling: '공시 수치와 핵심 키워드를 한 표에서 같이 봐서 긴 자료를 읽기 전에 전체 경쟁 구도를 빠르게 파악하게 됩니다.',
      insights: [
        '누가 규모와 수익성에서 우위인지 한 번에 비교할 수 있습니다.',
        '재무 값과 핵심 키워드를 같이 읽어 숫자와 메시지의 연결을 잡을 수 있습니다.',
      ],
      anchor: 'Peer 한눈 비교 표',
      position: 'left-[360px] top-[230px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[170px] h-[220px] w-[calc(100vw-390px)]',
    },
    {
      title: '핵심 비교 포인트',
      body: '중앙 왼쪽 영역은 사업 신호, 기술 신호, 리스크만 남겨 실무 비교에 바로 쓰는 문장으로 압축한 구간입니다. 느낌표를 열면 비교 에이전트가 어떤 공개 신호를 교차 검토해 이 세 축을 핵심 차이로 잡았는지 reasoning과 근거 카드로 확인할 수 있습니다.',
      userFeeling: '복잡한 비교 항목이 곧바로 제안 문장 수준으로 정리되어 있어 당장 보고나 논의에 써먹기 좋게 느껴집니다.',
      insights: [
        '사업 신호, 기술 신호, 리스크 축으로 나뉘어 있어 제안서나 회의 메모에 바로 옮겨 적기 좋은 비교 문장을 얻을 수 있습니다.',
        'SK AX와 선택 기업의 차이가 어느 축에서 벌어지는지 먼저 확인하고, 어떤 메시지로 대응해야 할지 초안을 빠르게 잡을 수 있습니다.',
        'reasoning 팝업으로 비교 문장이 어떤 공시, 기사, 카드 묶음에서 나왔는지 역추적할 수 있습니다.',
      ],
      anchor: 'Peer 비교 시사점',
      position: 'left-[360px] top-[430px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[380px] h-[300px] w-[calc(100vw-390px)]',
    },
    {
      title: 'SWOT 분석',
      body: '중앙 오른쪽 SWOT 보드는 같은 비교 결과를 전략 해석 관점으로 다시 정리한 영역입니다. 강점·약점·기회·위협을 각각 읽고, 느낌표를 통해 전략 에이전트가 어떤 문장을 대응 포인트로 압축했는지 reasoning으로 이어서 볼 수 있습니다.',
      userFeeling: '실무 비교와 전략 해석이 분리되어 있어 지금 필요한 판단과 더 길게 볼 포인트를 자연스럽게 나눠보게 됩니다.',
      insights: [
        '같은 비교 데이터를 강점·약점·기회·위협으로 다시 분해해 중장기 전략 논의용 프레임으로 전환할 수 있습니다.',
        '특정 경쟁사를 단순 비교하는 수준을 넘어서 SK AX에 어떤 기회와 위협으로 작동하는지 더 전략적으로 해석할 수 있습니다.',
        'SWOT 팝업으로 전략 에이전트가 어떤 카드와 시장 신호를 근거로 대응 포인트를 압축했는지 확인할 수 있습니다.',
      ],
      anchor: 'Peer 비교 시사점',
      position: 'right-[62px] top-[430px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[380px] h-[300px] w-[420px]',
    },
    {
      title: '사업 규모 × 매출 성장률',
      body: '전체 모드에서만 보이는 포지셔닝 그래프는 각 Peer를 사업 규모와 매출 성장률 두 축 위에 올려 시장 내 위치를 한눈에 보여줍니다. 표에서 본 숫자를 절대값이 아니라 상대 위치로 다시 읽게 해주는 시각화입니다.',
      userFeeling: '누가 크고 누가 빠르게 커지는지 좌표로 바로 보여서, 숫자를 하나씩 비교할 때보다 시장 판세가 훨씬 빠르게 들어옵니다.',
      insights: [
        '상단 표에서 규모가 큰 기업과 성장률이 높은 기업이 실제로 어떤 사분면에 몰려 있는지 바로 확인할 수 있습니다.',
        'SK AX가 시장 평균 대비 어느 위치에 있는지 보고, 추격 대상과 차별화 대상 기업을 빠르게 나눌 수 있습니다.',
        '필터가 전체일 때만 노출되므로 전체 시장 구조를 읽는 전용 단계로 활용하기 좋습니다.',
      ],
      anchor: 'Peer 포지셔닝',
      position: 'left-[360px] top-[760px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[700px] h-[360px] w-[calc(100vw-760px)]',
    },
    {
      title: '재무 체질 레이더',
      body: '레이더 차트는 수익성, 성장성, 운영 효율 등 여러 재무 축을 동시에 겹쳐 보여 주는 비교 영역입니다. 전체 모드에서는 주요 Peer를 함께 보고, 기업별 모드에서는 SK AX와 선택 기업의 체질 차이를 더 집중해서 읽게 됩니다.',
      userFeeling: '수치 표보다 차이가 더 시각적으로 드러나서 어떤 축이 강점이고 어떤 축이 약점인지 훨씬 직관적으로 파악하게 됩니다.',
      insights: [
        '수익성, 성장성, 운영 효율 같은 축의 차이를 모양으로 읽어 어느 기업이 어떤 체질을 갖는지 빠르게 이해할 수 있습니다.',
        '기업별 모드에서는 SK AX와 선택 기업의 약한 축이 어디인지 바로 드러나 대응 논의를 이어가기 좋습니다.',
        '표와 포지셔닝에서 본 차이를 레이더 모양으로 한 번 더 검증해 해석 신뢰도를 높일 수 있습니다.',
      ],
      anchor: '재무 체질 레이더',
      position: 'right-[58px] top-[760px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[700px] h-[360px] w-[420px]',
    },
  ],
  issues: [
    {
      title: '카드뉴스 필터',
      body: '상단 필터 영역에서는 Peer사, 섹터, 날짜, 키워드, 북마크 여부를 조합해 카드 목록을 좁혀 봅니다. 필터는 스크롤 중에도 상단에 고정되어 있기 때문에 긴 카드 목록을 보다가도 바로 조건을 다시 바꿀 수 있습니다.',
      userFeeling: '원하는 산업과 기업 뉴스만 빠르게 골라볼 수 있어 탐색 피로가 줄고, 지금 필요한 카드에 더 집중하게 됩니다.',
      insights: [
        '기업·섹터·날짜·키워드 기준으로 카드뉴스를 즉시 다시 좁힐 수 있습니다.',
        '북마크 카드만 따로 모아 다시 검토하는 용도로도 활용할 수 있습니다.',
      ],
      anchor: '카드뉴스 필터 영역',
      position: 'left-[330px] top-[142px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[112px] h-[92px] w-[calc(100vw-390px)]',
    },
    {
      title: '카드뉴스 그리드',
      body: '카드뉴스 목록은 커버, 날짜, 카테고리, Peer사 정보를 한 장에 압축해 보여주는 탐색 그리드입니다. 먼저 넓게 훑고 필요한 카드만 열어 상세 오버레이에서 요약, 시사점, 원문 링크까지 이어서 확인하는 구조입니다.',
      userFeeling: '긴 기사 원문으로 바로 들어가기 전에 핵심 정보만 넓게 스캔할 수 있어 탐색 속도가 훨씬 빨라집니다.',
      insights: [
        '산업과 경쟁사 관련 이슈를 카드 단위로 넓게 비교할 수 있습니다.',
        '제목과 메타 정보만으로도 어떤 주제가 반복되는지 감을 잡기 쉽습니다.',
      ],
      anchor: '카드뉴스 목록',
      position: 'left-[360px] top-[300px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[235px] h-[calc(100vh-330px)] w-[calc(100vw-390px)]',
    },
  ],
  mixer: [
    {
      title: '믹서 입력 조합',
      body: '믹서 작업 화면의 첫 단계에서는 Peer, 고객사, 산업, 키워드를 칩으로 조합합니다. 여기서 고른 입력 축이 어떤 카드가 후보로 남는지와 이후 결과가 어떤 관점으로 묶일지를 결정하며, 스크롤 중에도 상단에 고정되어 계속 조정할 수 있습니다.',
      userFeeling: '내가 중요하다고 보는 시장 축으로 직접 분석 조건을 설계하는 느낌이 들어, 단순 조회보다 훨씬 주도적으로 화면을 다루게 됩니다.',
      insights: [
        '같은 카드뉴스도 어떤 입력 조합을 먼저 고르느냐에 따라 전혀 다른 결과가 나옵니다.',
        '입력 단계 자체가 어떤 시나리오를 실험할지 가설을 세우는 출발점이 됩니다.',
      ],
      anchor: '믹서 선택 패널',
      position: 'left-[330px] top-[160px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[108px] h-[180px] w-[calc(100vw-700px)]',
    },
    {
      title: '카드뉴스 후보 선택',
      body: '중앙 카드 그리드에서는 입력 조건에 맞는 카드뉴스 후보를 실제 인풋으로 선택합니다. 선택한 카드와 북마크한 카드가 이후 결과 인사이트와 근거 카드뉴스에 다시 연결되므로, 결과의 출발점이 어디였는지가 분명하게 남습니다.',
      userFeeling: '내가 직접 고른 카드가 결과의 근거가 된다는 점이 명확해서, 이후에 나오는 인사이트를 더 설명 가능하게 받아들이게 됩니다.',
      insights: [
        '필터와 카드 선택이 함께 작동해 어떤 카드 묶음을 실험할지 설계할 수 있습니다.',
        '선택 카드가 결과 화면의 근거 카드뉴스와 그대로 이어집니다.',
      ],
      anchor: '카드뉴스 후보/북마크',
      position: 'left-[360px] top-[360px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[290px] h-[calc(100vh-360px)] w-[calc(100vw-430px)]',
    },
    {
      title: '입력 비율과 최근 결과',
      body: '오른쪽 패널에서는 현재 선택한 Peer와 카드 유형 비율을 도넛 차트로 보여줍니다. 한쪽 입력으로 너무 치우치지 않았는지 빠르게 점검하고, 아래 최근 결과 영역을 통해 믹서가 일회성 실행이 아니라 누적될 수 있는 구조라는 점을 이해하게 됩니다.',
      userFeeling: '결과를 만들기 전에 입력 균형을 점검할 수 있어 분석 과정이 더 안정적으로 느껴집니다.',
      insights: [
        '현재 입력 구성이 어느 쪽으로 기울었는지 바로 확인할 수 있습니다.',
        '최근 결과 영역을 통해 추후 누적 관리 흐름을 미리 이해할 수 있습니다.',
      ],
      anchor: '입력 비율 차트',
      position: 'right-[70px] top-[320px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[56px] top-[250px] h-[430px] w-[340px]',
    },
    {
      title: '믹서 결과 인사이트',
      body: '믹서를 실행하면 결과 화면 상단에 새 인사이트 카드가 정리됩니다. 여기서는 어떤 결론이 나왔는지 빠르게 훑고, 느낌표를 눌러 AI Agent가 어떤 카드 묶음을 수집하고 어떤 순서로 비교·압축했는지 reasoning 팝업으로 따로 열어 확인합니다.',
      userFeeling: '평소에는 결과를 짧게 읽다가 필요할 때만 추론 과정과 근거를 깊게 펼쳐볼 수 있어 부담 없이 탐색하게 됩니다.',
      insights: [
        '상단 인사이트 카드에서 핵심 결론을 먼저 비교할 수 있습니다.',
        'reasoning 팝업으로 에이전트의 수집·비교·요약 과정을 검증할 수 있습니다.',
      ],
      anchor: '믹서 결과 인사이트',
      position: 'left-[420px] top-[210px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[330px] top-[160px] h-[300px] w-[calc(100vw-840px)]',
    },
    {
      title: '결과 신호 분포와 근거 카드',
      body: '하단에서는 레이더 차트로 결과가 어떤 신호 구조로 묶였는지 읽고, 오른쪽 근거 카드뉴스에서 실제 반영된 카드만 다시 확인합니다. 결과 문장과 신호 분포, 원문 근거를 한 화면에서 교차 검증하는 마지막 단계입니다.',
      userFeeling: '새 인사이트가 단순 요약이 아니라 실제 카드뉴스 근거와 다시 연결되어 있어 결과를 더 신뢰하며 읽게 됩니다.',
      insights: [
        '레이더 차트로 어떤 축이 강하게 형성됐는지 빠르게 읽을 수 있습니다.',
        '근거 카드뉴스를 열어 결과가 어떤 기사 맥락에서 나왔는지 다시 확인할 수 있습니다.',
      ],
      anchor: '믹서 결과 신호 분포',
      position: 'left-[360px] top-[430px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[390px] h-[300px] w-[calc(100vw-760px)]',
    },
    {
      title: '믹서 기록',
      body: '전체 기록 보기로 이동하면 작업 화면과 분리된 히스토리 페이지가 열립니다. 왼쪽에서 시작일과 종료일을 직접 고르고, 오른쪽 스크롤 아카이브에서 기간 안에 포함된 결과를 날짜 단위로 다시 탐색하는 구조입니다.',
      userFeeling: '메인 작업 화면을 길게 늘리지 않고 기록 전용 공간에서 다시 보는 구조라 누적 데이터가 많아져도 훨씬 정돈된 느낌을 받게 됩니다.',
      insights: [
        '원하는 기간 범위만 남겨 과거 생성 결과를 다시 좁혀볼 수 있습니다.',
        '메인 믹서 작업과 기록 탐색이 분리되어 현재 작업 흐름을 덜 방해합니다.',
      ],
      anchor: '믹서 기록 날짜 필터',
      position: 'left-[330px] top-[180px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[132px] h-[340px] w-[300px]',
    },
  ],
  keywordGraph: [
    {
      title: '키워드 필터와 보기 전환',
      body: '상단 컨트롤에서는 기업, AX, 보안, 인프라, 수주 축으로 그래프를 좁히고 확대·축소, 3D 보기, 전체화면까지 함께 조절합니다. 같은 그래프를 어떤 초점으로 볼지 먼저 정하는 영역입니다.',
      userFeeling: '복잡한 관계망을 그대로 다 보지 않고 궁금한 축만 남겨 볼 수 있어 분석 초점이 훨씬 또렷해집니다.',
      insights: [
        '특정 기업군이나 주제 축만 남겨 연결 구조를 선택적으로 확인할 수 있습니다.',
        '2D/3D/전체화면 전환으로 복잡한 관계망을 더 읽기 쉬운 방식으로 바꿔 볼 수 있습니다.',
      ],
      anchor: '상단 컨트롤',
      position: 'right-[58px] top-[142px]',
      arrow: 'right-8 -top-3 border-l border-t',
      highlight: 'right-[48px] top-[104px] h-[92px] w-[520px]',
    },
    {
      title: '키워드 맵과 관련 카드뉴스',
      body: '그래프 본문에서는 기업, 산업, 세부 키워드가 관계망으로 펼쳐지고, 노드를 클릭하면 관련 카드뉴스 오버레이가 열립니다. 즉 관계 구조를 보고 바로 기사 근거로 내려가는 흐름이 같은 화면 안에서 이어집니다.',
      userFeeling: '시각화가 추상적인 그림에서 끝나지 않고 실제 카드뉴스로 바로 연결되어, 관계망이 근거 탐색 도구처럼 느껴집니다.',
      insights: [
        '현재 시장에서 중심이 되는 키워드와 연결 강도를 직관적으로 확인할 수 있습니다.',
        '특정 키워드가 어떤 기업, 어떤 주제와 동시에 묶여 있는지 관계 구조로 바로 파악할 수 있습니다.',
        '노드를 누르면 관련 카드뉴스까지 이어져 추상적인 관계를 실제 기사 맥락으로 곧바로 검증할 수 있습니다.',
      ],
      anchor: '2D 그래프 영역',
      position: 'left-[380px] top-[250px]',
      arrow: '-left-3 top-16 border-b border-l',
      highlight: 'left-[315px] top-[160px] h-[calc(100vh-240px)] w-[calc(100vw-680px)]',
    },
    {
      title: '키워드 상세 패널',
      body: '오른쪽 상세 패널은 선택한 키워드 하나를 기준으로 변화율, 분류, 출처, 연결 노드, 간단한 추이까지 다시 풀어 보여주는 보조 해석 영역입니다. 그래프에서 보인 관계를 숫자와 세부 맥락으로 좁혀 읽는 마지막 단계입니다.',
      userFeeling: '복잡한 맵에서 눈에 띄는 키워드를 발견한 뒤 그 의미를 바로 옆에서 더 깊게 풀어볼 수 있어 탐색 흐름이 끊기지 않습니다.',
      insights: [
        '전일 대비 변화율과 출처를 함께 보며 이 키워드가 일시적 반응인지 지속 신호인지 가늠할 수 있습니다.',
        'Connected 배지로 어떤 기업과 주제가 이 키워드 주변에 모여 있는지 빠르게 다시 확인할 수 있습니다.',
        '작은 추이 차트를 통해 오늘 튄 키워드가 최근 며칠간 어떤 흐름 위에서 올라온 것인지 보조적으로 읽을 수 있습니다.',
      ],
      anchor: '키워드 상세 패널',
      position: 'right-[58px] top-[290px]',
      arrow: 'right-[-12px] top-16 border-r border-t',
      highlight: 'right-[48px] top-[220px] h-[calc(100vh-320px)] w-[300px]',
    },
  ],
  settings: [
    {
      title: '설정 탭',
      body: '설정 화면은 회원 정보, 접속 로그, 알림 설정 세 가지 탭으로 구성됩니다. 왼쪽 탭에서 범주를 바꾸고, 오른쪽 본문에서 해당 영역의 입력값을 수정하거나 이력을 확인하는 구조입니다.',
      userFeeling: '프로필과 알림, 접속 이력을 한곳에서 나눠 관리할 수 있어 서비스가 더 개인화되고 관리 가능하게 느껴집니다.',
      insights: [
        '브리핑과 이벤트 알림을 내 업무 리듬에 맞게 조정할 수 있습니다.',
        '접속 로그를 통해 보안과 사용 이력을 함께 점검할 수 있습니다.',
      ],
      anchor: '설정 탭',
      position: 'left-[340px] top-[230px]',
      arrow: '-left-3 top-14 border-b border-l',
      highlight: 'left-[315px] top-[185px] h-[220px] w-[300px]',
    },
  ],
};

export const commonGuideSteps: ProductGuideStep[] = [
  searchGuideStep,
  {
    title: '업데이트와 알림',
    body: '상단 우측에서는 마지막 데이터 업데이트 시각과 알림 패널을 확인합니다. 알림을 열면 새로 들어온 변화, 브리핑 준비 상태, 추천 이동 경로를 보고 바로 해당 화면으로 이동할 수 있습니다.',
    userFeeling: '데이터가 언제 기준으로 갱신됐는지와 무엇이 새로 들어왔는지를 한 자리에서 확인할 수 있어 서비스 전반의 신뢰도가 높아집니다.',
    insights: [
      '새로 들어온 변화 신호와 브리핑 알림을 놓치지 않고 관련 화면으로 이동할 수 있습니다.',
      '현재 보고 있는 내용이 어느 시점까지 반영된 것인지 확인해 해석 기준 시점을 맞출 수 있습니다.',
    ],
    anchor: '업데이트와 알림',
    position: 'right-[56px] top-[126px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[48px] top-[92px] h-[64px] w-[260px]',
  },
  {
    title: '도움말 버튼',
    body: '물음표 버튼을 누르면 지금 보고 있는 화면 기준의 가이드가 다시 열립니다. 처음부터 다시 보거나 필요한 단계만 빠르게 확인할 때 쓰는 진입점입니다.',
    userFeeling: '헷갈리는 기능이 생겨도 같은 화면 안에서 바로 설명을 다시 열 수 있어 사용 흐름이 덜 끊깁니다.',
    insights: [
      '현재 화면에서 어떤 영역을 먼저 읽어야 하는지 다시 빠르게 확인할 수 있습니다.',
      '레이아웃이나 기능이 바뀌어도 가이드를 통해 바로 적응할 수 있습니다.',
    ],
    anchor: '도움말 버튼',
    position: 'right-[56px] top-[170px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[96px] top-[132px] h-[64px] w-[64px]',
  },
  {
    title: '프로필과 설정',
    body: '프로필 버튼을 누르면 설정 화면으로 이동해 회원 정보, 접속 로그, 알림 항목을 조정할 수 있습니다. 개인 기준으로 화면과 알림 환경을 맞추는 관리 진입점입니다.',
    userFeeling: '도움말 확인과 개인 환경 조정을 같은 상단 흐름 안에서 처리할 수 있어 사용 동선이 단순하게 느껴집니다.',
    insights: [
      '설정 화면으로 바로 이동해 알림 시간과 개인 환경을 조정할 수 있습니다.',
      '내 업무 방식에 맞는 기본 환경을 빠르게 유지할 수 있습니다.',
    ],
    anchor: '프로필·설정',
    position: 'right-[32px] top-[170px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[32px] top-[132px] h-[64px] w-[64px]',
  },
  {
    title: '사이드바 이동',
    body: '좌측 사이드바에서는 홈, 브리핑, Peer+, 카드뉴스, 믹서, 키워드 그래프 같은 주요 분석 화면으로 이동합니다. 현재 보고 있는 메뉴가 강조되어 있어 지금 어느 분석 단계에 있는지 바로 파악할 수 있습니다.',
    userFeeling: '여러 기능을 오가더라도 현재 위치를 잃지 않고 원하는 분석 화면으로 빠르게 전환할 수 있어 흐름이 안정적으로 느껴집니다.',
    insights: [
      '핵심 분석 화면을 같은 정보 흐름 안에서 오가며 비교할 수 있습니다.',
      '현재 보고 있는 화면과 다음 분석 단계의 연결 맥락을 유지할 수 있습니다.',
    ],
    anchor: '사이드바 메뉴',
    position: 'left-[260px] top-[260px]',
    arrow: '-left-3 top-16 border-b border-l',
    highlight: 'left-[12px] top-[84px] h-[calc(100vh-140px)] w-[220px]',
  },
  {
    title: 'AXIS AI 챗봇',
    body: '우측 하단 AI 챗봇은 현재 화면 내용을 질문형으로 다시 탐색하는 보조 도구입니다. 보고 있는 카드뉴스, 비교 화면, 브리핑 결과를 바탕으로 재설명, 요약, 후속 질문을 이어갈 수 있습니다.',
    userFeeling: '정적인 화면을 읽는 데서 멈추지 않고 필요한 내용을 바로 질문해 다시 설명받을 수 있어 이해 속도가 빨라집니다.',
    insights: [
      '복잡한 비교 결과나 카드 흐름을 대화형으로 다시 정리할 수 있습니다.',
      '현재 화면 내용을 바탕으로 보고용 문장이나 후속 질문을 빠르게 뽑아볼 수 있습니다.',
    ],
    anchor: 'AI 챗봇',
    position: 'right-[86px] bottom-[120px]',
    arrow: 'right-8 -top-3 border-l border-t',
    highlight: 'right-[48px] bottom-[48px] h-[72px] w-[72px]',
  },
];

export const guideTargetByAnchor: Record<string, string> = {
  '상단 검색창': 'global-search',
  '업데이트와 알림': 'topnav-notifications',
  '도움말 버튼': 'topnav-help',
  '프로필·설정': 'topnav-profile',
  '사이드바 메뉴': 'sidebar-nav',
  'AI 챗봇': 'ai-chat',
  '메인 인사이트 영역': 'home-insight',
  '오늘의 요약 카드뉴스': 'home-summary',
  '홈 차트 영역': 'home-charts',
  '좌측 상단 기간 컨트롤': 'briefing-period',
  '브리핑 본문': 'briefing-main',
  '브리핑 핵심 변화': 'briefing-focus',
  '브리핑 해석 흐름': 'insight-flow',
  '브리핑 해석 섹션': 'insight-analysis',
  '근거 카드뉴스 큐': 'briefing-evidence',
  'Peer+ 상단': 'peer-selector',
  'Peer 한눈 비교 표': 'peer-overview',
  'Peer 비교 시사점': 'peer-insight',
  'Peer 포지셔닝': 'peer-positioning',
  '재무 체질 레이더': 'peer-radar',
  '카드뉴스 필터 영역': 'cardnews-filter',
  '카드뉴스 목록': 'cardnews-grid',
  '믹서 선택 패널': 'mixer-input',
  '카드뉴스 후보/북마크': 'mixer-candidates',
  '입력 비율 차트': 'mixer-ratio',
  '믹서 결과 인사이트': 'mixer-result',
  '믹서 결과 신호 분포': 'mixer-signal-map',
  '결과 카드뉴스': 'mixer-evidence',
  '믹서 기록 날짜 필터': 'mixer-history-filter',
  '믹서 기록 스크롤 영역': 'mixer-history-archive',
  '키워드 필터': 'keyword-filter',
  '2D 그래프 영역': 'keyword-map',
  '노드 선택 결과': 'keyword-map',
  '키워드 상세 패널': 'keyword-detail',
  '상단 컨트롤': 'keyword-controls',
  '설정 탭': 'settings-tabs',
};
