export const uiText = {
  common: {
    viewAll: '전체 보기',
    loading: '데이터를 불러오는 중입니다.',
    loadError: '데이터를 불러오지 못했습니다.',
    cancel: '취소',
  },
  issues: {
    pageTitle: '동향 카드',
    pageSubtitle: 'Peer사별 사업 흐름과 검토 포인트를 카드 단위로 확인합니다.',
    searchPlaceholder: '동향 검색...',
    requestReport: '대시보드에서 보고서 요청',
    addTrend: '동향 추가',
    addTrendTitle: '동향 추가',
    peerFilter: 'Peer사:',
    reviewLevelFilter: '검토 수준:',
    addAction: '추가',
    addUrlPlaceholder: 'https://example.com/news/original-source',
    empty: '필터 조건에 맞는 동향이 없습니다.',
    loadFallback: '동향 데이터를 불러오지 못했습니다. 백엔드 연결 상태를 확인해 주세요.',
    loading: '동향 데이터를 불러오는 중입니다.',
    manualTitle: '원문 링크 기반 동향 분석 대기',
    manualPeer: '사용자 추가',
    manualSummaryOne: '사용자가 직접 추가한 원문 링크입니다.',
    manualSummaryTwo: 'AI 분석이 완료되면 Peer사, 검토 수준, 요약 내용이 자동으로 업데이트됩니다.',
  },
  issueCard: {
    reviewLabels: {
      urgent: '우선 검토',
      notable: '관찰 필요',
      reference: '배경 참고',
    },
    eventTypeLabels: {
      partnership: '파트너십',
      ma: 'M&A',
      personnel: '인사',
      tech: '기술',
      regulation: '규제',
      new_biz: '신규사업',
    },
    deleteConfirm: '이 동향 카드를 삭제하시겠습니까?',
    collapse: '간략히',
    expand: '상세보기',
    viewSource: '출처 보기',
    detailTitle: '상세 내용',
    implicationTitle: 'SK AX 관점 시사점',
    evidenceTitle: '판단 근거',
    actionTitle: '제안 액션',
    sourceTitle: '관련 출처',
    detailParagraphs: [
      '해당 동향은 단순한 기술 발표가 아니라, 대기업 고객의 업무 프로세스 안에 AI를 상시 운영 체계로 넣으려는 움직임입니다.',
      'AXIS는 ① SK AX 핵심 사업과의 연관성, ② 고객군 중복 가능성, ③ 가격·파트너십·레퍼런스 변화, ④ 단기 영업 대응 필요성을 기준으로 검토 수준을 산정합니다.',
      '원문 기사, 기업 보도자료, 관련 후속 기사 간 표현 차이가 있을 수 있으므로 실제 계약 규모와 고객 적용 범위는 담당자 검수가 필요합니다.',
    ],
    implications: [
      '전략적 중요도: SK AX가 강조하는 AI Transformation, Agentic AI, 산업별 실행 시나리오와 직접 비교될 수 있는 경쟁 메시지입니다.',
      '시장 영향: 고객은 단순 AI 기능보다 보안, 운영, 변화관리까지 묶인 패키지를 요구할 가능성이 높습니다.',
      '검토 질문: 타깃 계정과의 중첩 여부와 산업별 차별 포인트를 함께 확인해야 합니다.',
    ],
    evidenceCards: [
      { title: '사업 연관성', body: 'SK AX의 Agentic AI 및 산업 AX 메시지와 직접 비교 가능' },
      { title: '고객군 중복', body: '제조, 금융, 공공 고객군에서 제안 경쟁 가능성 높음' },
      { title: '확산 흐름', body: '후속 기사와 유사 키워드가 함께 증가해 연속 관찰이 필요' },
    ],
    actions: [
      { title: '1. 타깃 계정 영향도 확인', body: '제조, 금융, 공공 고객 중 해당 경쟁 메시지와 겹치는 계정 목록 점검' },
      { title: '2. SK AX 차별화 메시지 보강', body: 'Agentic AI 적용 시나리오, 운영 거버넌스, 산업 특화 성과 지표를 제안 자료에 반영' },
      { title: '3. 후속 기사 모니터링', body: '실제 고객명, 구축 범위, 투자 규모가 확인되는 기사 발생 시 즉시 알림' },
    ],
    sources: [
      { title: '삼성 SDS, 제조·금융 생성형 AI 운영 플랫폼 레퍼런스 확대', meta: '연합뉴스 · 2026.04.22', url: 'https://example.com/samsung-sds-openai' },
      { title: '대기업 AX 운영 플랫폼 경쟁 심화 분석', meta: '전자신문 · 2026.04.22', url: 'https://example.com/samsung-sds-gpt4-enterprise' },
    ],
  },
  peers: {
    pageTitle: 'Peer사 분석',
    pageSubtitle: '경쟁사별 동향 방향, SK AX 영향도, 후속 모니터링 포인트',
    basisTitle: '분석 기준',
    periodUnit: '기간 단위',
    periodValue: '기준 값',
    peerListTitle: 'Peer사 목록',
    addPeer: '추가',
    addPeerTitle: 'Peer사 추가',
    companyPlaceholder: '회사명',
    keywordPlaceholder: '모니터링 키워드, 쉼표로 구분',
    register: '등록',
    noAnalysisTitle: 'IR 자료 분석',
    noAnalysisBody: '아직 등록된 IR 분석 내용이 없습니다. 자료 업로드 또는 분석 완료 후 이 영역에 기업별 전략 방향과 사업 포트폴리오가 표시됩니다.',
    primary: '우선 검토',
    watch: '관찰 필요',
    high: '높음',
    medium: '중간',
    waitingDirection: 'AI Agent 분석 대기 중입니다. 뉴스 수집이 완료되면 Peer사의 동향이 자동 요약됩니다.',
    waitingImplication: '수집 데이터와 내부 기준을 바탕으로 SK AX 관점 시사점이 생성됩니다.',
  },
  rawArticles: {
    pageTitle: '원문 아카이브',
    pageSubtitle: '수집된 원문 기사와 출처 링크',
    filter: '필터',
    filtered: '선택한 조건이 원문 목록에 적용되었습니다.',
    openLink: '바로가기',
    headers: ['제목', 'Peer사', '출처', '원문 작성 시간', '원문 링크'],
  },
  alerts: {
    pageTitle: '알림 센터',
    pageSubtitle: '관심 키워드와 중요 시그널로 생성된 웹 알림',
    historyTab: '알림 목록',
    rulesTab: '알림 설정',
    historyTitle: '최근 웹 알림',
    rulesTitle: '알림 기준',
    ruleEditorTitle: '관심 키워드',
    emptyRuleTitle: '등록된 관심 키워드가 없습니다',
    emptyRuleBody: '설정 화면에서 관심 키워드를 등록하면 카드뉴스 매칭 시 알림이 생성됩니다.',
    addRule: '키워드 추가',
    ruleName: '키워드',
    condition: '생성 기준',
    channel: '표시 위치',
    saveRule: '알림 기준 저장',
    enabled: '활성',
    disabled: '비활성',
    sent: '확인 완료',
    pending: '안읽음',
    lastTriggered: '생성 시각',
    newRuleName: '새 관심 키워드',
  },
  dashboard: {
    pageTitle: 'Dashboard',
    pageSubtitle: 'SK AX 전략기획 관점 Peer Intelligence',
    trendQueueLabel: 'Trend Queue',
    trendSectionTitle: '최근 주요 동향',
    topArticlesLabel: 'Top Articles',
    topArticlesTitle: '주요로 살펴볼 기사',
    keywordsTitle: '오늘의 키워드',
    keywordsNewsCountLabel: '분석 대상 뉴스',
    keywordsGuide: '키워드를 눌러 연관 문서와 대화형 검색으로 이동',
    openSearch: '탐색 열기',
    keywordVolumeTitle: '섹터 검색 관심도 추이',
    keywordVolumeSubtitle: '시간대별 내부 검색량 기준',
    realtime: '실시간',
    current: '현재',
    articleArchive: '기사 아카이브',
    chatTitle: 'AXIS AI',
    chatSubtitle: '대화형 전략 검색 · 질의응답',
    chatGreeting: '안녕하세요. AXIS입니다. Peer사 동향, 핵심 키워드, 최근 카드뉴스에 대해 편하게 질문해 주세요.',
    chatResponse:
      '요청하신 내용을 기준으로 최근 Peer사 동향, SK AX 영향도, 후속 검토 포인트를 함께 정리해드릴게요.',
    chatPlaceholder: '예: 이번 주 금융권 경쟁 동향 요약해줘',
  },
  briefings: {
    pageTitle: '브리핑',
    pageSubtitle: '전략기획팀이 매일과 주간 단위로 확인할 Peer사 핵심 동향과 근거 자료',
    dailyTab: '일간 브리핑',
    weeklyTab: '주간 브리핑',
    todayDailyTitle: '오늘의 일간 브리핑',
    thisWeekTitle: '이번 주 브리핑 요약',
    requestReport: '대시보드에서 보고서 요청',
    evidenceTitle: '근거 명시',
    historyTitle: '과거 브리핑',
    filter: '필터',
    delivered: '전송 완료',
    peerFilter: 'Peer사',
    keywordFilter: '키워드',
    dateFilter: '기간',
  },
} as const;
